http {
  upstream user_service_backend {
    # Balanceo de carga para user_service (3 réplicas)
    server user_service_1:5000;
    server user_service_2:5000;
    server user_service_3:5000;
  }

  upstream ticket_service_backend {
    # Balanceo de carga para ticket_service (3 réplicas)
    server ticket_service_1:5100;
    server ticket_service_2:5100;
    server ticket_service_3:5100;
  }

  upstream area_service_backend {
    # Balanceo de carga para area_service (3 réplicas)
    server area_service_1:5200;
    server area_service_2:5200;
    server area_service_3:5200;
  }

  upstream loan_service_backend {
    # Balanceo de carga para loan_service (3 réplicas)
    server loan_service_1:5300;
    server loan_service_2:5300;
    server loan_service_3:5300;
  }

  upstream subnets_service_backend {
    # Balanceo de carga para subnets_service (3 réplicas)
    server subnets_service_1:5400;
    server subnets_service_2:5400;
    server subnets_service_3:5400;
  }

  upstream real_state_service_backend {
    # Balanceo de carga para real_state_service (3 réplicas)
    server real_state_service_1:5500;
    server real_state_service_2:5500;
    server real_state_service_3:5500;
  }

  upstream notifications_service_backend {
    # Balanceo de carga para notifications_service (3 réplicas)
    server notifications_service_1:5601;
    server notifications_service_2:5601;
    server notifications_service_3:5601;
  }

  server {
    listen 80;
    
    location /user {
      proxy_pass http://user_service_backend;
    }

    location /ticket {
      proxy_pass http://ticket_service_backend;
    }

    location /area {
      proxy_pass http://area_service_backend;
    }

    location /loan {
      proxy_pass http://loan_service_backend;
    }

    location /subnets {
      proxy_pass http://subnets_service_backend;
    }

    location /real_state {
      proxy_pass http://real_state_service_backend;
    }

    location /notifications {
      proxy_pass http://notifications_service_backend;
    }
  }
}
